package net.iceattack.dyablewoodmod.datagen;

import net.iceattack.dyablewoodmod.DyableWoodMod;
import net.iceattack.dyablewoodmod.block.ModBlocks;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.neoforged.neoforge.common.data.BlockTagsProvider;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagsProvider extends BlockTagsProvider {
    public ModBlockTagsProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider) {
        super(output, lookupProvider, DyableWoodMod.MOD_ID);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        tag(BlockTags.MINEABLE_WITH_AXE)
                .add(ModBlocks.getRK(ModBlocks.BLUE_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.LIME_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.PINK_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.PURPLE_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.RED_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.WHITE_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.YELLOW_PLANKS.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.LIME_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.LIME_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.PINK_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.PINK_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.RED_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.RED_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_STAIRS.get()))
                .add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_SLAB.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.LIME_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.LIME_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.PINK_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.PINK_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.RED_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.RED_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_BUTTON.get()))
                .add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_PRESSURE_PLATE.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.LIME_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.LIME_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.PINK_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.PINK_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.RED_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.RED_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_FENCE.get()))
                .add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_FENCE_GATE.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_ACACIA_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_ACACIA_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_BIRCH_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_BIRCH_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_DARK_OAK_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_DARK_OAK_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_JUNGLE_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_JUNGLE_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_OAK_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_OAK_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_SPRUCE_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLUE_SPRUCE_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_ACACIA_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_ACACIA_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_BIRCH_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_BIRCH_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_DARK_OAK_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_DARK_OAK_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_JUNGLE_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_JUNGLE_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_OAK_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_OAK_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_SPRUCE_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BLACK_SPRUCE_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_ACACIA_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_ACACIA_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_BIRCH_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_BIRCH_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_DARK_OAK_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_DARK_OAK_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_JUNGLE_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_JUNGLE_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_OAK_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_OAK_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_SPRUCE_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.BROWN_SPRUCE_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_ACACIA_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_ACACIA_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_BIRCH_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_BIRCH_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_DARK_OAK_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_DARK_OAK_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_JUNGLE_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_JUNGLE_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_OAK_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_OAK_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_SPRUCE_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.CYAN_SPRUCE_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_ACACIA_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_ACACIA_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_BIRCH_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_BIRCH_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_DARK_OAK_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_DARK_OAK_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_JUNGLE_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_JUNGLE_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_OAK_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_OAK_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_SPRUCE_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GRAY_SPRUCE_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_ACACIA_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_ACACIA_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_BIRCH_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_BIRCH_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_DARK_OAK_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_DARK_OAK_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_JUNGLE_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_JUNGLE_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_OAK_DOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_OAK_TRAPDOOR.get()))
                .add(ModBlocks.getRK(ModBlocks.GREEN_SPRUCE_DOOR.get()));

        // Mineable with axe tag ^^^

        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_SLAB.get()));
        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_SLAB.get()));
        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_SLAB.get()));
        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_SLAB.get()));
        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_SLAB.get()));
        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_SLAB.get()));
        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_SLAB.get()));
        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_SLAB.get()));
        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_SLAB.get()));
        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.LIME_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.LIME_WOOD_SLAB.get()));
        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_SLAB.get()));
        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_SLAB.get()));
        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.PINK_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.PINK_WOOD_SLAB.get()));
        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_SLAB.get()));
        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.RED_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.RED_WOOD_SLAB.get()));
        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_SLAB.get()));
        tag(BlockTags.STAIRS)
                .add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_STAIRS.get()));
        tag(BlockTags.SLABS)
                .add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_SLAB.get()));

        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_PRESSURE_PLATE.get()));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_PRESSURE_PLATE.get()));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_PRESSURE_PLATE.get()));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_PRESSURE_PLATE.get()));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_PRESSURE_PLATE.get()));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_PRESSURE_PLATE.get()));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_PRESSURE_PLATE.get()));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_PRESSURE_PLATE.get()));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_PRESSURE_PLATE.get()));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.LIME_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.LIME_WOOD_PRESSURE_PLATE.get()));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_PRESSURE_PLATE.get()));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_PRESSURE_PLATE.get()));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.PINK_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.PINK_WOOD_PRESSURE_PLATE.get()));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_PRESSURE_PLATE.get()));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.RED_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.RED_WOOD_PRESSURE_PLATE.get()));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_PRESSURE_PLATE.get()));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_BUTTON.get()));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_PRESSURE_PLATE.get()));

        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_FENCE_GATE.get()));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_FENCE_GATE.get()));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_FENCE_GATE.get()));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_FENCE_GATE.get()));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_FENCE_GATE.get()));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_FENCE_GATE.get()));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_FENCE_GATE.get()));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_FENCE_GATE.get()));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_FENCE_GATE.get()));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.LIME_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.LIME_WOOD_FENCE_GATE.get()));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_FENCE_GATE.get()));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_FENCE_GATE.get()));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.PINK_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.PINK_WOOD_FENCE_GATE.get()));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_FENCE_GATE.get()));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.RED_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.RED_WOOD_FENCE_GATE.get()));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_FENCE_GATE.get()));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_FENCE.get()));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_FENCE_GATE.get()));

        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLUE_ACACIA_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLUE_ACACIA_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLUE_BIRCH_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLUE_BIRCH_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLUE_DARK_OAK_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLUE_DARK_OAK_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLUE_JUNGLE_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLUE_JUNGLE_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLUE_OAK_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLUE_OAK_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLUE_SPRUCE_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLUE_SPRUCE_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLACK_ACACIA_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLACK_ACACIA_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLACK_BIRCH_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLACK_BIRCH_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLACK_DARK_OAK_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLACK_DARK_OAK_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLACK_JUNGLE_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLACK_JUNGLE_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLACK_OAK_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLACK_OAK_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLACK_SPRUCE_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLACK_SPRUCE_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BROWN_ACACIA_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BROWN_ACACIA_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BROWN_BIRCH_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BROWN_BIRCH_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BROWN_DARK_OAK_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BROWN_DARK_OAK_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BROWN_JUNGLE_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BROWN_JUNGLE_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BROWN_OAK_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BROWN_OAK_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BROWN_SPRUCE_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BROWN_SPRUCE_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.CYAN_ACACIA_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.CYAN_ACACIA_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.CYAN_BIRCH_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.CYAN_BIRCH_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.CYAN_DARK_OAK_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.CYAN_DARK_OAK_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.CYAN_JUNGLE_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.CYAN_JUNGLE_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.CYAN_OAK_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.CYAN_OAK_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.CYAN_SPRUCE_DOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GRAY_ACACIA_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GRAY_ACACIA_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GRAY_BIRCH_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GRAY_BIRCH_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GRAY_DARK_OAK_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GRAY_DARK_OAK_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GRAY_JUNGLE_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GRAY_JUNGLE_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GRAY_OAK_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GRAY_OAK_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GRAY_SPRUCE_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GRAY_SPRUCE_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GREEN_ACACIA_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GREEN_ACACIA_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GREEN_BIRCH_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GREEN_BIRCH_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GREEN_DARK_OAK_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GREEN_DARK_OAK_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GREEN_JUNGLE_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GREEN_JUNGLE_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GREEN_OAK_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GREEN_OAK_TRAPDOOR.get()));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GREEN_SPRUCE_DOOR.get()));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GREEN_SPRUCE_TRAPDOOR.get()));





    }
}
