package net.iceattack.dyablewoodmod.datagen;

import net.iceattack.dyablewoodmod.block.ModBlocks;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.loot.BlockLootSubProvider;
import net.minecraft.world.flag.FeatureFlagSet;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;

import java.util.Set;

public class ModBlockLootTableProvider extends BlockLootSubProvider {
    public ModBlockLootTableProvider(HolderLookup.Provider registries) {
        super(Set.of(), FeatureFlags.REGISTRY.allFlags(), registries);
    }

    @Override
    protected void generate() {
        dropSelf(ModBlocks.BLUE_PLANKS.get());
        dropSelf(ModBlocks.BLACK_PLANKS.get());
        dropSelf(ModBlocks.BROWN_PLANKS.get());
        dropSelf(ModBlocks.CYAN_PLANKS.get());
        dropSelf(ModBlocks.GRAY_PLANKS.get());
        dropSelf(ModBlocks.GREEN_PLANKS.get());
        dropSelf(ModBlocks.LIGHT_BLUE_PLANKS.get());
        dropSelf(ModBlocks.LIGHT_GRAY_PLANKS.get());
        dropSelf(ModBlocks.LIGHT_PURPLE_PLANKS.get());
        dropSelf(ModBlocks.LIME_PLANKS.get());
        dropSelf(ModBlocks.MAGENTA_PLANKS.get());
        dropSelf(ModBlocks.ORANGE_PLANKS.get());
        dropSelf(ModBlocks.PINK_PLANKS.get());
        dropSelf(ModBlocks.PURPLE_PLANKS.get());
        dropSelf(ModBlocks.RED_PLANKS.get());
        dropSelf(ModBlocks.WHITE_PLANKS.get());
        dropSelf(ModBlocks.YELLOW_PLANKS.get());

        dropSelf(ModBlocks.BLUE_WOOD_STAIRS.get());
        add(ModBlocks.BLUE_WOOD_SLAB.get(), this::createSlabItemTable);
        dropSelf(ModBlocks.BLACK_WOOD_STAIRS.get());
        add(ModBlocks.BLACK_WOOD_SLAB.get(), this::createSlabItemTable);
        dropSelf(ModBlocks.BROWN_WOOD_STAIRS.get());
        add(ModBlocks.BROWN_WOOD_SLAB.get(), this::createSlabItemTable);
        dropSelf(ModBlocks.CYAN_WOOD_STAIRS.get());
        add(ModBlocks.CYAN_WOOD_SLAB.get(), this::createSlabItemTable);
        dropSelf(ModBlocks.GRAY_WOOD_STAIRS.get());
        add(ModBlocks.GRAY_WOOD_SLAB.get(), this::createSlabItemTable);
        dropSelf(ModBlocks.GREEN_WOOD_STAIRS.get());
        add(ModBlocks.GREEN_WOOD_SLAB.get(), this::createSlabItemTable);
        dropSelf(ModBlocks.LIGHT_BLUE_WOOD_STAIRS.get());
        add(ModBlocks.LIGHT_BLUE_WOOD_SLAB.get(), this::createSlabItemTable);
        dropSelf(ModBlocks.LIGHT_GRAY_WOOD_STAIRS.get());
        add(ModBlocks.LIGHT_GRAY_WOOD_SLAB.get(), this::createSlabItemTable);
        dropSelf(ModBlocks.LIGHT_PURPLE_WOOD_STAIRS.get());
        add(ModBlocks.LIGHT_PURPLE_WOOD_SLAB.get(), this::createSlabItemTable);
        dropSelf(ModBlocks.LIME_WOOD_STAIRS.get());
        add(ModBlocks.LIME_WOOD_SLAB.get(), this::createSlabItemTable);
        dropSelf(ModBlocks.MAGENTA_WOOD_STAIRS.get());
        add(ModBlocks.MAGENTA_WOOD_SLAB.get(), this::createSlabItemTable);
        dropSelf(ModBlocks.ORANGE_WOOD_STAIRS.get());
        add(ModBlocks.ORANGE_WOOD_SLAB.get(), this::createSlabItemTable);
        dropSelf(ModBlocks.PINK_WOOD_STAIRS.get());
        add(ModBlocks.PINK_WOOD_SLAB.get(), this::createSlabItemTable);
        dropSelf(ModBlocks.PURPLE_WOOD_STAIRS.get());
        add(ModBlocks.PURPLE_WOOD_SLAB.get(), this::createSlabItemTable);
        dropSelf(ModBlocks.RED_WOOD_STAIRS.get());
        add(ModBlocks.RED_WOOD_SLAB.get(), this::createSlabItemTable);
        dropSelf(ModBlocks.WHITE_WOOD_STAIRS.get());
        add(ModBlocks.WHITE_WOOD_SLAB.get(), this::createSlabItemTable);
        dropSelf(ModBlocks.YELLOW_WOOD_STAIRS.get());
        add(ModBlocks.YELLOW_WOOD_SLAB.get(), this::createSlabItemTable);

        dropSelf(ModBlocks.BLUE_WOOD_PRESSURE_PLATE.get());
        dropSelf(ModBlocks.BLUE_WOOD_BUTTON.get());
        dropSelf(ModBlocks.BLACK_WOOD_BUTTON.get());
        dropSelf(ModBlocks.BLACK_WOOD_PRESSURE_PLATE.get());
        dropSelf(ModBlocks.BROWN_WOOD_BUTTON.get());
        dropSelf(ModBlocks.BROWN_WOOD_PRESSURE_PLATE.get());
        dropSelf(ModBlocks.CYAN_WOOD_BUTTON.get());
        dropSelf(ModBlocks.CYAN_WOOD_PRESSURE_PLATE.get());
        dropSelf(ModBlocks.GRAY_WOOD_BUTTON.get());
        dropSelf(ModBlocks.GRAY_WOOD_PRESSURE_PLATE.get());
        dropSelf(ModBlocks.GREEN_WOOD_BUTTON.get());
        dropSelf(ModBlocks.GREEN_WOOD_PRESSURE_PLATE.get());
        dropSelf(ModBlocks.LIGHT_BLUE_WOOD_BUTTON.get());
        dropSelf(ModBlocks.LIGHT_BLUE_WOOD_PRESSURE_PLATE.get());
        dropSelf(ModBlocks.LIGHT_GRAY_WOOD_BUTTON.get());
        dropSelf(ModBlocks.LIGHT_GRAY_WOOD_PRESSURE_PLATE.get());
        dropSelf(ModBlocks.LIGHT_PURPLE_WOOD_BUTTON.get());
        dropSelf(ModBlocks.LIGHT_PURPLE_WOOD_PRESSURE_PLATE.get());
        dropSelf(ModBlocks.LIME_WOOD_BUTTON.get());
        dropSelf(ModBlocks.LIME_WOOD_PRESSURE_PLATE.get());
        dropSelf(ModBlocks.MAGENTA_WOOD_BUTTON.get());
        dropSelf(ModBlocks.MAGENTA_WOOD_PRESSURE_PLATE.get());
        dropSelf(ModBlocks.ORANGE_WOOD_BUTTON.get());
        dropSelf(ModBlocks.ORANGE_WOOD_PRESSURE_PLATE.get());
        dropSelf(ModBlocks.PINK_WOOD_BUTTON.get());
        dropSelf(ModBlocks.PINK_WOOD_PRESSURE_PLATE.get());
        dropSelf(ModBlocks.PURPLE_WOOD_BUTTON.get());
        dropSelf(ModBlocks.PURPLE_WOOD_PRESSURE_PLATE.get());
        dropSelf(ModBlocks.RED_WOOD_BUTTON.get());
        dropSelf(ModBlocks.RED_WOOD_PRESSURE_PLATE.get());
        dropSelf(ModBlocks.WHITE_WOOD_BUTTON.get());
        dropSelf(ModBlocks.WHITE_WOOD_PRESSURE_PLATE.get());
        dropSelf(ModBlocks.YELLOW_WOOD_BUTTON.get());
        dropSelf(ModBlocks.YELLOW_WOOD_PRESSURE_PLATE.get());

        dropSelf(ModBlocks.BLUE_WOOD_FENCE.get());
        dropSelf(ModBlocks.BLUE_WOOD_FENCE_GATE.get());
        dropSelf(ModBlocks.BLACK_WOOD_FENCE.get());
        dropSelf(ModBlocks.BLACK_WOOD_FENCE_GATE.get());
        dropSelf(ModBlocks.BROWN_WOOD_FENCE.get());
        dropSelf(ModBlocks.BROWN_WOOD_FENCE_GATE.get());
        dropSelf(ModBlocks.CYAN_WOOD_FENCE.get());
        dropSelf(ModBlocks.CYAN_WOOD_FENCE_GATE.get());
        dropSelf(ModBlocks.GRAY_WOOD_FENCE.get());
        dropSelf(ModBlocks.GRAY_WOOD_FENCE_GATE.get());
        dropSelf(ModBlocks.GREEN_WOOD_FENCE.get());
        dropSelf(ModBlocks.GREEN_WOOD_FENCE_GATE.get());
        dropSelf(ModBlocks.LIGHT_BLUE_WOOD_FENCE.get());
        dropSelf(ModBlocks.LIGHT_BLUE_WOOD_FENCE_GATE.get());
        dropSelf(ModBlocks.LIGHT_GRAY_WOOD_FENCE.get());
        dropSelf(ModBlocks.LIGHT_GRAY_WOOD_FENCE_GATE.get());
        dropSelf(ModBlocks.LIGHT_PURPLE_WOOD_FENCE.get());
        dropSelf(ModBlocks.LIGHT_PURPLE_WOOD_FENCE_GATE.get());
        dropSelf(ModBlocks.LIME_WOOD_FENCE.get());
        dropSelf(ModBlocks.LIME_WOOD_FENCE_GATE.get());
        dropSelf(ModBlocks.MAGENTA_WOOD_FENCE.get());
        dropSelf(ModBlocks.MAGENTA_WOOD_FENCE_GATE.get());
        dropSelf(ModBlocks.ORANGE_WOOD_FENCE.get());
        dropSelf(ModBlocks.ORANGE_WOOD_FENCE_GATE.get());
        dropSelf(ModBlocks.PINK_WOOD_FENCE.get());
        dropSelf(ModBlocks.PINK_WOOD_FENCE_GATE.get());
        dropSelf(ModBlocks.PURPLE_WOOD_FENCE.get());
        dropSelf(ModBlocks.PURPLE_WOOD_FENCE_GATE.get());
        dropSelf(ModBlocks.RED_WOOD_FENCE.get());
        dropSelf(ModBlocks.RED_WOOD_FENCE_GATE.get());
        dropSelf(ModBlocks.WHITE_WOOD_FENCE.get());
        dropSelf(ModBlocks.WHITE_WOOD_FENCE_GATE.get());
        dropSelf(ModBlocks.YELLOW_WOOD_FENCE.get());
        dropSelf(ModBlocks.YELLOW_WOOD_FENCE_GATE.get());

        add(ModBlocks.BLUE_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BLUE_ACACIA_TRAPDOOR.get());
        add(ModBlocks.BLUE_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BLUE_BIRCH_TRAPDOOR.get());
        add(ModBlocks.BLUE_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BLUE_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.BLUE_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BLUE_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.BLUE_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BLUE_OAK_TRAPDOOR.get());
        add(ModBlocks.BLUE_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BLUE_SPRUCE_TRAPDOOR.get());
        add(ModBlocks.BLACK_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BLACK_ACACIA_TRAPDOOR.get());
        add(ModBlocks.BLACK_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BLACK_BIRCH_TRAPDOOR.get());
        add(ModBlocks.BLACK_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BLACK_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.BLACK_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BLACK_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.BLACK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BLACK_OAK_TRAPDOOR.get());
        add(ModBlocks.BLACK_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BLACK_SPRUCE_TRAPDOOR.get());
        add(ModBlocks.BROWN_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BROWN_ACACIA_TRAPDOOR.get());
        add(ModBlocks.BROWN_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BROWN_BIRCH_TRAPDOOR.get());
        add(ModBlocks.BROWN_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BROWN_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.BROWN_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BROWN_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.BROWN_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BROWN_OAK_TRAPDOOR.get());
        add(ModBlocks.BROWN_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.BROWN_SPRUCE_TRAPDOOR.get());
        add(ModBlocks.CYAN_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.CYAN_ACACIA_TRAPDOOR.get());
        add(ModBlocks.CYAN_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.CYAN_BIRCH_TRAPDOOR.get());
        add(ModBlocks.CYAN_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.CYAN_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.CYAN_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.CYAN_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.CYAN_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.CYAN_OAK_TRAPDOOR.get());
        add(ModBlocks.CYAN_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.CYAN_SPRUCE_TRAPDOOR.get());
        add(ModBlocks.GRAY_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.GRAY_ACACIA_TRAPDOOR.get());
        add(ModBlocks.GRAY_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.GRAY_BIRCH_TRAPDOOR.get());
        add(ModBlocks.GRAY_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.GRAY_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.GRAY_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.GRAY_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.GRAY_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.GRAY_OAK_TRAPDOOR.get());
        add(ModBlocks.GRAY_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.GRAY_SPRUCE_TRAPDOOR.get());
        add(ModBlocks.GREEN_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.GREEN_ACACIA_TRAPDOOR.get());
        add(ModBlocks.GREEN_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.GREEN_BIRCH_TRAPDOOR.get());
        add(ModBlocks.GREEN_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.GREEN_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.GREEN_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.GREEN_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.GREEN_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.GREEN_OAK_TRAPDOOR.get());
        add(ModBlocks.GREEN_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.GREEN_SPRUCE_TRAPDOOR.get());
        add(ModBlocks.LIGHT_BLUE_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_BLUE_ACACIA_TRAPDOOR.get());
        add(ModBlocks.LIGHT_BLUE_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_BLUE_BIRCH_TRAPDOOR.get());
        add(ModBlocks.LIGHT_BLUE_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_BLUE_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.LIGHT_BLUE_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_BLUE_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.LIGHT_BLUE_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_BLUE_OAK_TRAPDOOR.get());
        add(ModBlocks.LIGHT_BLUE_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_BLUE_SPRUCE_TRAPDOOR.get());
        add(ModBlocks.LIGHT_GRAY_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_GRAY_ACACIA_TRAPDOOR.get());
        add(ModBlocks.LIGHT_GRAY_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_GRAY_BIRCH_TRAPDOOR.get());
        add(ModBlocks.LIGHT_GRAY_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_GRAY_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.LIGHT_GRAY_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_GRAY_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.LIGHT_GRAY_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_GRAY_OAK_TRAPDOOR.get());
        add(ModBlocks.LIGHT_GRAY_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_GRAY_SPRUCE_TRAPDOOR.get());
        add(ModBlocks.LIGHT_PURPLE_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_PURPLE_ACACIA_TRAPDOOR.get());
        add(ModBlocks.LIGHT_PURPLE_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_PURPLE_BIRCH_TRAPDOOR.get());
        add(ModBlocks.LIGHT_PURPLE_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_PURPLE_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.LIGHT_PURPLE_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_PURPLE_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.LIGHT_PURPLE_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_PURPLE_OAK_TRAPDOOR.get());
        add(ModBlocks.LIGHT_PURPLE_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIGHT_PURPLE_SPRUCE_TRAPDOOR.get());
        add(ModBlocks.LIME_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIME_ACACIA_TRAPDOOR.get());
        add(ModBlocks.LIME_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIME_BIRCH_TRAPDOOR.get());
        add(ModBlocks.LIME_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIME_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.LIME_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIME_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.LIME_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIME_OAK_TRAPDOOR.get());
        add(ModBlocks.LIME_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.LIME_SPRUCE_TRAPDOOR.get());
        add(ModBlocks.MAGENTA_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.MAGENTA_ACACIA_TRAPDOOR.get());
        add(ModBlocks.MAGENTA_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.MAGENTA_BIRCH_TRAPDOOR.get());
        add(ModBlocks.MAGENTA_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.MAGENTA_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.MAGENTA_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.MAGENTA_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.MAGENTA_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.MAGENTA_OAK_TRAPDOOR.get());
        add(ModBlocks.MAGENTA_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.MAGENTA_SPRUCE_TRAPDOOR.get());
        add(ModBlocks.ORANGE_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.ORANGE_ACACIA_TRAPDOOR.get());
        add(ModBlocks.ORANGE_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.ORANGE_BIRCH_TRAPDOOR.get());
        add(ModBlocks.ORANGE_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.ORANGE_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.ORANGE_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.ORANGE_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.ORANGE_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.ORANGE_OAK_TRAPDOOR.get());
        add(ModBlocks.ORANGE_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.ORANGE_SPRUCE_TRAPDOOR.get());
        add(ModBlocks.PINK_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.PINK_ACACIA_TRAPDOOR.get());
        add(ModBlocks.PINK_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.PINK_BIRCH_TRAPDOOR.get());
        add(ModBlocks.PINK_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.PINK_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.PINK_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.PINK_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.PINK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.PINK_OAK_TRAPDOOR.get());
        add(ModBlocks.PINK_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.PINK_SPRUCE_TRAPDOOR.get());
        add(ModBlocks.PURPLE_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.PURPLE_ACACIA_TRAPDOOR.get());
        add(ModBlocks.PURPLE_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.PURPLE_BIRCH_TRAPDOOR.get());
        add(ModBlocks.PURPLE_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.PURPLE_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.PURPLE_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.PURPLE_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.PURPLE_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.PURPLE_OAK_TRAPDOOR.get());
        add(ModBlocks.PURPLE_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.PURPLE_SPRUCE_TRAPDOOR.get());
        add(ModBlocks.RED_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.RED_ACACIA_TRAPDOOR.get());
        add(ModBlocks.RED_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.RED_BIRCH_TRAPDOOR.get());
        add(ModBlocks.RED_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.RED_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.RED_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.RED_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.RED_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.RED_OAK_TRAPDOOR.get());
        add(ModBlocks.RED_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.RED_SPRUCE_TRAPDOOR.get());
        add(ModBlocks.WHITE_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.WHITE_ACACIA_TRAPDOOR.get());
        add(ModBlocks.WHITE_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.WHITE_BIRCH_TRAPDOOR.get());
        add(ModBlocks.WHITE_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.WHITE_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.WHITE_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.WHITE_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.WHITE_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.WHITE_OAK_TRAPDOOR.get());
        add(ModBlocks.WHITE_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.WHITE_SPRUCE_TRAPDOOR.get());
        add(ModBlocks.YELLOW_ACACIA_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.YELLOW_ACACIA_TRAPDOOR.get());
        add(ModBlocks.YELLOW_BIRCH_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.YELLOW_BIRCH_TRAPDOOR.get());
        add(ModBlocks.YELLOW_DARK_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.YELLOW_DARK_OAK_TRAPDOOR.get());
        add(ModBlocks.YELLOW_JUNGLE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.YELLOW_JUNGLE_TRAPDOOR.get());
        add(ModBlocks.YELLOW_OAK_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.YELLOW_OAK_TRAPDOOR.get());
        add(ModBlocks.YELLOW_SPRUCE_DOOR.get(), this::createDoorTable);
        dropSelf(ModBlocks.YELLOW_SPRUCE_TRAPDOOR.get());


    }

    @Override
    protected Iterable<Block> getKnownBlocks() {
        return ModBlocks.BLOCKS.getEntries().stream().map(Holder::value)::iterator;
    }
}
