package net.iceattack.dyablewoodmod.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagsProvider;
import net.iceattack.dyablewoodmod.block.ModBlocks;
import net.minecraft.core.HolderLookup;
import net.minecraft.tags.BlockTags;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagsProvider extends FabricTagsProvider.BlockTagsProvider {
    public ModBlockTagsProvider(FabricPackOutput output, CompletableFuture<HolderLookup.Provider> registryLookupFuture) {
        super(output, registryLookupFuture);
    }

    @Override
    protected void addTags(HolderLookup.Provider registries) {
        tag(BlockTags.MINEABLE_WITH_AXE)
                .add(ModBlocks.getRK(ModBlocks.BLACK_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.BLUE_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.BROWN_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.CYAN_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.GRAY_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.GREEN_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.LIME_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.PINK_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.PURPLE_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.RED_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.WHITE_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.YELLOW_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.LIME_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.LIME_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.PINK_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.PINK_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.RED_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.RED_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_STAIRS))
                .add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_SLAB))
                .add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.LIME_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.LIME_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.PINK_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.PINK_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.RED_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.RED_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_BUTTON))
                .add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_PRESSURE_PLATE))
                .add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.LIME_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.LIME_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.PINK_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.PINK_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.RED_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.RED_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_FENCE))
                .add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_FENCE_GATE))
                .add(ModBlocks.getRK(ModBlocks.BLUE_ACACIA_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BLUE_ACACIA_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BLUE_BIRCH_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BLUE_BIRCH_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BLUE_DARK_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BLUE_DARK_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BLUE_JUNGLE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BLUE_JUNGLE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BLUE_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BLUE_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BLUE_SPRUCE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BLUE_SPRUCE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BLACK_ACACIA_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BLACK_ACACIA_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BLACK_BIRCH_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BLACK_BIRCH_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BLACK_DARK_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BLACK_DARK_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BLACK_JUNGLE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BLACK_JUNGLE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BLACK_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BLACK_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BLACK_SPRUCE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BLACK_SPRUCE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BROWN_ACACIA_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BROWN_ACACIA_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BROWN_BIRCH_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BROWN_BIRCH_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BROWN_DARK_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BROWN_DARK_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BROWN_JUNGLE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BROWN_JUNGLE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BROWN_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BROWN_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.BROWN_SPRUCE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.BROWN_SPRUCE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.CYAN_ACACIA_DOOR))
                .add(ModBlocks.getRK(ModBlocks.CYAN_ACACIA_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.CYAN_BIRCH_DOOR))
                .add(ModBlocks.getRK(ModBlocks.CYAN_BIRCH_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.CYAN_DARK_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.CYAN_DARK_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.CYAN_JUNGLE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.CYAN_JUNGLE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.CYAN_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.CYAN_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.CYAN_SPRUCE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.CYAN_SPRUCE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.GRAY_ACACIA_DOOR))
                .add(ModBlocks.getRK(ModBlocks.GRAY_ACACIA_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.GRAY_BIRCH_DOOR))
                .add(ModBlocks.getRK(ModBlocks.GRAY_BIRCH_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.GRAY_DARK_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.GRAY_DARK_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.GRAY_JUNGLE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.GRAY_JUNGLE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.GRAY_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.GRAY_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.GRAY_SPRUCE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.GRAY_SPRUCE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.GREEN_ACACIA_DOOR))
                .add(ModBlocks.getRK(ModBlocks.GREEN_ACACIA_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.GREEN_BIRCH_DOOR))
                .add(ModBlocks.getRK(ModBlocks.GREEN_BIRCH_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.GREEN_DARK_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.GREEN_DARK_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.GREEN_JUNGLE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.GREEN_JUNGLE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.GREEN_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.GREEN_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.GREEN_SPRUCE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.GREEN_SPRUCE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_ACACIA_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_ACACIA_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_BIRCH_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_BIRCH_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_DARK_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_DARK_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_JUNGLE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_JUNGLE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_SPRUCE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_SPRUCE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_ACACIA_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_ACACIA_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_BIRCH_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_BIRCH_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_DARK_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_DARK_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_JUNGLE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_JUNGLE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_SPRUCE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_SPRUCE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_ACACIA_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_ACACIA_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_BIRCH_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_BIRCH_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_DARK_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_DARK_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_JUNGLE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_JUNGLE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_SPRUCE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_SPRUCE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIME_ACACIA_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIME_ACACIA_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIME_BIRCH_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIME_BIRCH_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIME_DARK_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIME_DARK_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIME_JUNGLE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIME_JUNGLE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIME_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIME_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.LIME_SPRUCE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.LIME_SPRUCE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_ACACIA_DOOR))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_ACACIA_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_BIRCH_DOOR))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_BIRCH_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_DARK_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_DARK_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_JUNGLE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_JUNGLE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_SPRUCE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_SPRUCE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_ACACIA_DOOR))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_ACACIA_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_BIRCH_DOOR))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_BIRCH_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_DARK_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_DARK_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_JUNGLE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_JUNGLE_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_OAK_DOOR))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_OAK_TRAPDOOR))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_SPRUCE_DOOR))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_SPRUCE_TRAPDOOR));

        // Makes blocks mineable with pickaxe ^^^^


        tag(BlockTags.PLANKS)
                .add(ModBlocks.getRK(ModBlocks.BLACK_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.BLUE_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.BROWN_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.CYAN_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.GRAY_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.GREEN_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.LIME_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.MAGENTA_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.ORANGE_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.PINK_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.PURPLE_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.RED_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.WHITE_PLANKS))
                .add(ModBlocks.getRK(ModBlocks.YELLOW_PLANKS));

        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_SLAB));
        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_SLAB));
        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_SLAB));
        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_SLAB));
        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_SLAB));
        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_SLAB));
        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_SLAB));
        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_SLAB));
        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_SLAB));
        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.LIME_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.LIME_WOOD_SLAB));
        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_SLAB));
        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_SLAB));
        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.PINK_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.PINK_WOOD_SLAB));
        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_SLAB));
        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.RED_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.RED_WOOD_SLAB));
        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_SLAB));
        tag(BlockTags.STAIRS).add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_STAIRS));
        tag(BlockTags.SLABS).add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_SLAB));

        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_PRESSURE_PLATE));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_PRESSURE_PLATE));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_PRESSURE_PLATE));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_PRESSURE_PLATE));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_PRESSURE_PLATE));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_PRESSURE_PLATE));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_PRESSURE_PLATE));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_PRESSURE_PLATE));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_PRESSURE_PLATE));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.LIME_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.LIME_WOOD_PRESSURE_PLATE));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_PRESSURE_PLATE));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_PRESSURE_PLATE));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.PINK_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.PINK_WOOD_PRESSURE_PLATE));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_PRESSURE_PLATE));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.RED_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.RED_WOOD_PRESSURE_PLATE));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_PRESSURE_PLATE));
        tag(BlockTags.BUTTONS).add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_BUTTON));
        tag(BlockTags.WOODEN_PRESSURE_PLATES).add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_PRESSURE_PLATE));

        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.BLUE_WOOD_FENCE_GATE));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.BLACK_WOOD_FENCE_GATE));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.BROWN_WOOD_FENCE_GATE));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.CYAN_WOOD_FENCE_GATE));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.GRAY_WOOD_FENCE_GATE));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.GREEN_WOOD_FENCE_GATE));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_WOOD_FENCE_GATE));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_WOOD_FENCE_GATE));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_WOOD_FENCE_GATE));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.LIME_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.LIME_WOOD_FENCE_GATE));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.MAGENTA_WOOD_FENCE_GATE));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.ORANGE_WOOD_FENCE_GATE));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.PINK_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.PINK_WOOD_FENCE_GATE));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.PURPLE_WOOD_FENCE_GATE));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.RED_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.RED_WOOD_FENCE_GATE));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.WHITE_WOOD_FENCE_GATE));
        tag(BlockTags.WOODEN_FENCES).add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_FENCE));
        tag(BlockTags.FENCE_GATES).add(ModBlocks.getRK(ModBlocks.YELLOW_WOOD_FENCE_GATE));

        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLUE_ACACIA_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLUE_ACACIA_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLUE_BIRCH_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLUE_BIRCH_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLUE_DARK_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLUE_DARK_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLUE_JUNGLE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLUE_JUNGLE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLUE_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLUE_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLUE_SPRUCE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLUE_SPRUCE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLACK_ACACIA_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLACK_ACACIA_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLACK_BIRCH_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLACK_BIRCH_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLACK_DARK_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLACK_DARK_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLACK_JUNGLE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLACK_JUNGLE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLACK_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLACK_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BLACK_SPRUCE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BLACK_SPRUCE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BROWN_ACACIA_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BROWN_ACACIA_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BROWN_BIRCH_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BROWN_BIRCH_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BROWN_DARK_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BROWN_DARK_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BROWN_JUNGLE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BROWN_JUNGLE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BROWN_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BROWN_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.BROWN_SPRUCE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.BROWN_SPRUCE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.CYAN_ACACIA_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.CYAN_ACACIA_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.CYAN_BIRCH_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.CYAN_BIRCH_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.CYAN_DARK_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.CYAN_DARK_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.CYAN_JUNGLE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.CYAN_JUNGLE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.CYAN_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.CYAN_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.CYAN_SPRUCE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.CYAN_SPRUCE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GRAY_ACACIA_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GRAY_ACACIA_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GRAY_BIRCH_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GRAY_BIRCH_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GRAY_DARK_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GRAY_DARK_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GRAY_JUNGLE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GRAY_JUNGLE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GRAY_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GRAY_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GRAY_SPRUCE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GRAY_SPRUCE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GREEN_ACACIA_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GREEN_ACACIA_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GREEN_BIRCH_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GREEN_BIRCH_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GREEN_DARK_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GREEN_DARK_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GREEN_JUNGLE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GREEN_JUNGLE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GREEN_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GREEN_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.GREEN_SPRUCE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.GREEN_SPRUCE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_ACACIA_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_ACACIA_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_BIRCH_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_BIRCH_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_DARK_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_DARK_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_JUNGLE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_JUNGLE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_SPRUCE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_BLUE_SPRUCE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_ACACIA_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_ACACIA_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_BIRCH_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_BIRCH_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_DARK_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_DARK_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_JUNGLE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_JUNGLE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_SPRUCE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_GRAY_SPRUCE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_ACACIA_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_ACACIA_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_BIRCH_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_BIRCH_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_DARK_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_DARK_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_JUNGLE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_JUNGLE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_SPRUCE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIGHT_PURPLE_SPRUCE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIME_ACACIA_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIME_ACACIA_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIME_BIRCH_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIME_BIRCH_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIME_DARK_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIME_DARK_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIME_JUNGLE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIME_JUNGLE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIME_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIME_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.LIME_SPRUCE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.LIME_SPRUCE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.MAGENTA_ACACIA_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.MAGENTA_ACACIA_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.MAGENTA_BIRCH_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.MAGENTA_BIRCH_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.MAGENTA_DARK_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.MAGENTA_DARK_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.MAGENTA_JUNGLE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.MAGENTA_JUNGLE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.MAGENTA_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.MAGENTA_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.MAGENTA_SPRUCE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.MAGENTA_SPRUCE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.ORANGE_ACACIA_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.ORANGE_ACACIA_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.ORANGE_BIRCH_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.ORANGE_BIRCH_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.ORANGE_DARK_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.ORANGE_DARK_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.ORANGE_JUNGLE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.ORANGE_JUNGLE_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.ORANGE_OAK_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.ORANGE_OAK_TRAPDOOR));
        tag(BlockTags.WOODEN_DOORS).add(ModBlocks.getRK(ModBlocks.ORANGE_SPRUCE_DOOR));
        tag(BlockTags.WOODEN_TRAPDOORS).add(ModBlocks.getRK(ModBlocks.ORANGE_SPRUCE_TRAPDOOR));




    }
}
